services:
  app:
    image: todo-front-prod-image
    ports:
      - 5173:80
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    container_name: todo-front-prod-container
    environment:
      VITE_BACKEND_URL: 'http://localhost:8080/api/'
  debug-helper:
    image: busybox
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8000
    container_name: reverse-proxy
    depends_on:
      - app
      - server
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes:
      - ./todo-backend/redis_data:/data

  server:
    image: todo-backend-prod-image
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: todo-backend-prod-container
    environment:
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database # Correcting the username and password
    ports:
      - 3000:3000
    volumes:
      - ./todo-backend:/usr/src/app
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local
  node_modules:
