services:
  app:
    build:
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    command: ['npm', 'run', 'dev', '--', '--host']
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./:/usr/src/app
    depends_on: [redis, mongo]
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  my-debugger:
    image: busybox

volumes:
  mongo_data:
  redis_data:
  node_modules:
